version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    steps:
      - checkout
      - run:
          name: Tests
          command: |
                   cd src
                   dotnet test AssertNet.Core.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=bin
                   dotnet test AssertNet.Xunit.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutputDirectory=bin
      - run:
          name: Codecov
          command: |
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.Core.Tests/bin/coverage.xml" -t $CODECOV_KEY
                   bash <(curl -s https://codecov.io/bash) -f "src/AssertNet.Xunit.Tests/bin/coverage.xml" -t $CODECOV_KEY
